services:

  web:
    build:
      args:
        - NODEMON_VERSION=${NODEMON_VERSION:-3.1.7}
      context: .
      dockerfile: Dockerfile.dev
    command: tail -f /dev/null
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    env_file:
      - .env
      # - path: .env.override
      #   required: false

  db:
    image: mysql:8.0.30-debian
    env_file:
      - .env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: mysqldatabase