include:
  - ./external-api/docker-compose.external-api.yaml

services:
  web1:
    extends:
      file: docker-compose.common.yaml
      service: web
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  
  db:
    extends:
      file: docker-compose.common.yaml
      service: db
    tmpfs:
      - /var/lib/mysql
    