services:
  web:
    build:
      args:
        - NODEMON_VERSION=${NODEMON_VERSION:-3.1.7}
      context: .
      dockerfile: Dockerfile.dev
    command: ["./start.sh"]
    volumes:
      - .:/home/node/app
    env_file:
      - .env.example
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: mysql:8.0.30-debian
    restart: always
    env_file:
      - .env.example
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: mysqldatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
